#pragma once
#include "001-TwoSum.h"
#include "002-MinStack.h"
#include "003-MaxStack.h"
#include "004-ReverseLinkedList.h"
#include "005-TreeConstruction.h"
#include "006-FlipTree.h"
#include "007-BSTFromPreOrder.h"
#include "008-MergeKLinkedLists.h"